### ISSUE TITLE
Why define all Errors in 'application'?

### ISSUE THREAD

**Issue by mroobert** [mikaelvesavuori/get-a-room-ddd-example#1]
Why would we define all errors in the  **application layer** since the **domain** should not have dependencies to the outer layers ?

If we look in the source code at **code/Reservation/Reservation/src/domain/valueObjects/TimeSlot.ts** we have this dependency inside **domain**:

```ts
import { InvalidHourCountError } from '../../application/errors/InvalidHourCountError';
```

**Comment by mikaelvesavuori** [comment]
Hey @mroobert,

This is a really good question that I've circled around in various ways many times before. In this project, yes you are correct that the errors are in the application layer.

One of the things that isn't crystal clear (to me!) in Clean Architecture is how we should handle "meta functionality" like interfaces and errors. In this project, my thinking was that errors apply to the application scope rather than the domain scope (which I still think is somewhat correct).

However, given that I have "solved" the problem for interfaces/types by simply having a folder `interfaces` — and we have other meta functionality in `frameworks` (the lowest level utilities and such; furthest removed from the domain) — I am considering simply adding a `src/errors` folder as a recommendation.

It's certainly possible to argue that errors _are domain constructs_ but I disagree: a typology of code is by itself not contingent on any particular logical level. They might as well point to some decidedly non-domain error, like an `ApiFetchError` or something else (a completely made-up example).

It's important to not get caught on orthodoxy, and add pragmatism when necessary. In the case of interfaces and errors, they are _expected_ to be used as/when needed, whereas the other "onion layers" are for handling application flow; which I decidedly think errors and interfaces aren't a part of, in similar terms.

Alas, the domain level would still be dependent on a lower level, but again, it already is by way of interfaces etc., which we can't really get rid of in any way I find intuitive or improves on our application architecture.

Good catch and let's see if I get time to change this structure.

**Comment by mroobert** [comment]
Thanks, great response!
